### 📢 Apoie este projeto!

Se você gosta deste projeto e deseja apoiá-lo, considere fazer uma doação! 💙 Sua contribuição ajuda a manter o desenvolvimento ativo e a adicionar novas funcionalidades.

[![Apoie no GitHub Sponsors](https://img.shields.io/badge/Apoie_no-GitHub_Sponsors-brightgreen)](https://github.com/sponsors/Jonhvmp)
